### PR TITLE
add cookie generation to login

### PR DESCRIPTION
**Pull request by debboutr**
this uses a new package `vue-cookies` that sets a cookie for both username and password if the checkbox is checked when logging in. The cookie's validation time will be determined by a new environment variable. I am unable to reproduce exactly what Chris is seeing as when I log in to vue I can open a new tab and not be prompted, so I don't know that this will really work until we see it in production. If the cookies exist after the user has been logged out, they will be used to log the user in again during the `fetchUser`  action in the auth module. There is no way that I can figure to test this, but I used a short `SESSION_COOKIE_AGE` setting in django to have the `sessionid` fail after a few seconds. You can then set the env var `VUE_APP_COOKIE_DURATION` in vuejs to something in seconds to see how they work together. There is another setting in the global config for VueCookies that we may use to enforce it being an `https` root that may be useful, but I don't know how useful it would be.

`https://www.npmjs.com/package/vue-cookies#set-global-config`

We might also think of hashing the password when the cookie is being set with a package like `crypto`, but again, I'm not really a site security professional.

### CODE REVIEW

**Review by michael-barbour — COMMENTED** [review]
https://stackoverflow.com/questions/2100356/is-it-secure-to-store-passwords-in-cookies

First glance it looks like the strategy of saving username and passwords in cookies is greatly frowned upon.  This makes sense as anybody using that computer could accidentally stumble upon your credentials.

I think we can circumvent this by letting django handle the session.  If you throw a `request.session.set_expiry(31536000)` in front of the login in `chemreg.auth.views.LoginView` you can prevent the session from expiring for a year. (set your .env `SESSION_COOKIE_AGE` real low to test this)

```python
    def post(self, request):
        """Log the user in."""
        request.session.set_expiry(31536000)
        login(request, request.user)
        return self.response(request)
```

From there you could just check for an body param for "remember_me"

`set_expiry(0)` is [supposed to be able](https://docs.djangoproject.com/en/3.1/topics/http/sessions/#django.contrib.sessions.backends.base.SessionBase.set_expiry) to forbid logging out entirely but i cant seem to make that work.

I don't know if this is any better.  Having a bunch of never-expiring keys may be just as bad of a security flaw.

**Review by michael-barbour — CHANGES_REQUESTED** [review]
I've found a few bugs.  I've added a short description of each bug then steps to replicate below.

1. It looks like logging out does not clear the cookies.  When I log out and try to navigate to a new page as an anonymous user, the cookies automatically log me back in.  These issues would probably be addressed by deleting the cookies on logout.

2. When the token would have usually timed out, the user's navigation is always forced back to the homepage.  Say a user spent a long time on `/substances` then navigates to `/vocabularies`, rather than navigating to vocabularies they will be redirected to the home screen.

3. When editing a substance, compound or synonym, if the user's session would have expired, the user is unable to submit.  This bug is the most "out of scope" due to the complex and bespoke error handling on each post/patch.  If it's not going to be addressed here it will probably require additional tickets to resolve.

**Note:** Setting the django `SESSION_COOKIE_AGE`  `.env` variable to a single digit number to expire sessions after only a few seconds makes this easier to test.  `.env` variables are not hot loaded so you'll have to reload your server session. (runserver, gunicorn, docker)

## Testing

To test with our current set up, you could write mocked 403s returned from the django server.  Currently in order to validate the session before making any navigation changes, our server requests the current user from the current user session with `/login`.  Using 
```Javascript
cy.route({
      method: "GET",
      url: "/login",
      status: 403,
      response: { detail : "Authentication credentials were not provided." }
    }).as("validation")
cy.route({
      method: "POST",
      url: "/login",
      status: 200,
      response: { user-data } 
    }).as("reauthentication")
```
Should simulate the actions re-authentication actions without affecting the actual session cookie at all.

That said these tests would be pretty tightly tied to the way we authenticate before every page access.  I can't say these tests wouldn't be too brittle to be useful or that they would even accurately replicate the browser's activity.

## Steps to replicate logout bug:

### Method One

1. Log in with "Remember Me" checked.
2. Log out
3. Navigate to a new page.  ie `Substances` on the navbar.

Results: User is logged back in by the act of navigating to a new page

### Method Two

1. Log in with "Remember Me" checked.
2. Navigate to a new page.  ie `Substances` on the navbar.
3. Log out

Results:  User is not logged out but navigated to the home page.

## Steps to replicate navigation bug:

1. Log in with "Remember Me" checked.
2. Wait for session to expire
3. Navigate to a new page.  ie `Substances` on the navbar.

Results:  User is instead navigated to the home page.


## Steps to replicate editing bug:

1. Log in with "Remember Me" checked.
2. Navigate to Substances before the session expires (otherwise the search will break according to bug 2.
3. Search "Sample Substance 2".
4. Edit and attempt to save the Substance, Compound or Synonym.

Results:  Compound and Synonym return errors requesting Authentication.  Substance "403"s out but has no error message

**Comment by debboutr** [comment]
for issue #3 that you mention above, should we just `dispatch("auth/fetchUser")` before every post that we make? we do that in navigation?

**Comment by michael-barbour** [comment]
> for issue #3 that you mention above, should we just `dispatch("auth/fetchUser")` before every post that we make? we do that in navigation? we could just add it to every one of the the `store/actions.js`?

That makes sense to me.  I think we may need a re-authentication function there at some point anyways.

**Comment by michael-barbour** [comment]
Closing PR due to ticket being closed.  Per @dmlyons2 
https://github.com/Chemical-Curation/chemcurator_vuejs/issues/90#issuecomment-763796398

**Pull request closed without merging**
