### PR TITLE
138 clear compound

### LINKED ISSUE #138: When selecting substance from sidebar, compound is nulled if appropriate
**As a** *user*
**I want** *the compound to be nulled out if a substance is read into the substance page that has no compound*
**So that** *I understand the substance better when browsing chemicals*

**Acceptance Criteria:**
When I select a DTXSID from the sidebar on the substance page or arrive on one from a search, the compound displayed always represents the substance that is loaded (including no structure if there is no structure

**Test(s):**

### PR DESCRIPTION
**Pull request by stevenhausman-gdit**
Closes #138 

Fixes issue when opening a substance that has no compound after a substance that does. The compound data would persist.

The test "should show substance link with mismatched DTXCID=>DTXSID" made use of compound data persistence. Reworked.

Added simple test to check for presence of compound.

### CODE REVIEW

**Comment by stevenhausman-gdit** [comment]
To demonstrate:
**Pre-Fix**

1. Search for "Sample Substance" - this has a compound.
2. Search for "Solo Substance" - this has no compound.
3. The compound associated with "Sample Substance" is shown with "Solo Substance" instead of no compound.

**Post-Fix**
1. Search for "Sample Substance" - this has a compound.
2. Search for "Solo Substance" - this has no compound.
3. Since there is no compound associated with "Solo Substance" the `compound` object is reset.

**Review by mwfrost — CHANGES_REQUESTED** [review]
The compound associated with the right side of the page is still lurking somewhere in the page's state.

1. Navigate to "Sample substance," which is DTXSID502000000, linked to the compound `DTXCID302000003`
2. Let the page load, then search for "Solo substance," or `DTXSID202000099`, which is not linked to a compound
3. Once the page loads, pull down the Structure Type menu and click "Defined Compound"
In my environment, this is causing ketcher to reload the structure for `DTXCID302000003`, and it shows the blue hyperlink to indicate that the compound is linked to a different substance.

**Review by debboutr — APPROVED** [review]
looks good, I removed the section of the test that posts a defined-compound that doesn't yet exist as it need to query the API and is failing on dev as well.

**Review by mwfrost — APPROVED** [review]
Approved after updates

**Pull request merged**
